name: "Update the repo with the latest approved schemas"

on:
  workflow_dispatch

jobs:
  update-schemas:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Get issues with 'schema-approved' label"
        uses: actions/github-script@v5
        id: get_approved_issues
        with:
          script: |
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: 'schema-approved',
              state: 'open'
            });
            return issues.data.map(issue => issue.number).join(',');
        
      - name: "Run the 'update-schemas' action script"
        uses: ./.github/actions/update-schemas
        id: update_schemas
        with:
          repo_path: ${{ github.repository }}
          issue_list: ${{ steps.get_approved_issues.outputs.result }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}